# Generated by Django 5.1.1 on 2024-09-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenartechapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='overall_total_marks',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
