# Generated by Django 5.1.1 on 2024-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenartechapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='overall_total_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_marks_term_one',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_marks_term_three',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_marks_term_two',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='cutOfPoint',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
