# Generated by Django 5.1.1 on 2024-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenartechapp', '0002_alter_student_overall_total_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
