# Generated by Django 5.1.1 on 2024-09-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenartechapp', '0002_alter_student_overall_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='hod_remarks',
            field=models.TextField(default='Very Good'),
        ),
        migrations.AlterField(
            model_name='student',
            name='conduct',
            field=models.TextField(default='Very Good'),
        ),
        migrations.AlterField(
            model_name='student',
            name='remarks',
            field=models.TextField(default='Very Good'),
        ),
    ]
