# Generated by Django 5.1.1 on 2024-10-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenartechapp', '0003_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_completed',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
