# Generated by Django 5.1.1 on 2024-09-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenartechapp', '0003_term_hod_remarks_alter_student_conduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='cutOfPoint',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
