# Generated by Django 5.1.1 on 2024-09-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenartechapp', '0004_term_cutofpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='cutOfPoint',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
