# Generated by Django 5.1.1 on 2024-10-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenartechapp', '0004_student_year_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
