# Generated by Django 5.1.1 on 2024-10-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cenartechapp', '0005_student_attendance3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendance3',
        ),
    ]
