# Generated by Django 5.1.1 on 2024-10-18 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenartechapp', '0007_school_customuser_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittedstudents',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cenartechapp.school'),
        ),
        migrations.AddField(
            model_name='passedstudents',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cenartechapp.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cenartechapp.school'),
        ),
        migrations.AddField(
            model_name='term',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cenartechapp.school'),
        ),
        migrations.AddField(
            model_name='yearlyadmittedstudents',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cenartechapp.school'),
        ),
        migrations.AddField(
            model_name='yearlypassedstudents',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cenartechapp.school'),
        ),
    ]
