# Generated by Django 5.1.1 on 2024-10-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cenartechapp', '0009_school_number_school_slogan'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
