# Generated by Django 5.1.1 on 2024-10-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenartechapp', '0010_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='deactivate',
            field=models.BooleanField(default=False),
        ),
    ]
