# Generated by Django 5.1.1 on 2024-10-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenartechapp', '0011_school_deactivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('HOD', 'HOD'), ('STAFF', 'STAFF'), ('STUDENT', 'STUDENT'), ('ADMIN', 'ADMIN')], default='ADMIN', max_length=50),
        ),
    ]
